version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: acai-delivery-postgres
    environment:
      POSTGRES_DB: acaideliverydb
      POSTGRES_USER: acaiuser
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: